### ISSUE TITLE
how to use multi-gpu training?

### ISSUE THREAD

**Issue by Bo396543018** [fredzzhang/hicodet#15]
When I use CUDA_VISIBLE_DEVICES=0,1,2,3,4 python train_detector.py，the ValueError: In training mode, targets should be passed raise? Is this code only support single gpu training?

**Comment by fredzzhang** [comment]
Hi, @Bo396543018 

Unfortunately yes. I did not implement support for multi-gpu training at the time. I might do this sometime in the future, but definitely not soon...

If you are keen, you can take a look at [this script](https://github.com/fredzzhang/vcoco/blob/main/detections/train_detector.py). I implemented DDP for fine-tuning the detector on V-COCO. The code is not well optimised yet, but you should be able to adapt it for HICO-DET.

Cheers,
Fred

**Comment by Bo396543018** [comment]
Thank you @fredzzhang , I'll try it
