### ISSUE TITLE
wrong images for repair bike?

### ISSUE THREAD

**Issue by monacv** [fredzzhang/hicodet#16]
Hi do you know why we have wrong images for repair bike?
data/hico_20160224_det/images/train2015/HICO_train2015_00030009.jpg
![Screenshot from 2021-04-23 17-06-26](https://user-images.githubusercontent.com/76495162/115929736-482d4080-a456-11eb-98d7-f562136ac0ca.png)
this is not repair but has repair bike and carry bike labels

this image clearly is not repairing or carrying a bike

**Comment by fredzzhang** [comment]
Hi, @monacv 

I think the labels for this image are `ride bicycle` and `hold bicycle`. Note that labels have been converted to zero-based index in this repo.

Hope that answers your question. But do bear in mind that there are indeed many missing and incorrect annotations in this dataset, though the particular instance you mentioned is not one of them.

Cheers,
Fred
