### ISSUE TITLE
Can I replace coco with my own dataset?How should I do?

### ISSUE THREAD

**Issue by ahong007007** [fredzzhang/hicodet#18]
Thank you for your perf work.

Can I replace vcoco/HOI-DET with my own dataset?How should I do?

thanks

**Comment by fredzzhang** [comment]
Hi @ahong007007,

The dataset implementation is [here](https://github.com/fredzzhang/hicodet/blob/main/hicodet.py). You can use it as a template to create your own dataset. The most important part is to make sure `__getitem__` returns data in the exact same format. You also need a method to return a list that contains the valid target classes for each object type, same as `object_to_verb()` at line 169.

Fred.
