### ISSUE TITLE
The annotation tool. 

### ISSUE THREAD

**Issue by BakingBrains** [fredzzhang/hicodet#21]
Do you have any other demo, because I have gone through the annotation tool link which you have provided in one of the issues. There is no proper documentation on how can we annotate on our custom dataset or images. Could you please suggest if any??

**Comment by fredzzhang** [comment]
Hi @BakingBrains,

I assume you are referring to #20. There are a series of video tutorials linked in the repository. You can find it [here](https://www.youtube.com/playlist?list=PLD-7XrNHCcFLv938DO4yYcTrgaff9BJjN).

Cheers,
Fred.
