### ISSUE TITLE
Regarding the script to convert annotations to .json

### ISSUE THREAD

**Issue by BakingBrains** [fredzzhang/hicodet#23]
Can you please provide the script to convert the HICO-Det Dataset annotations from matlab format to json format.

**Comment by fredzzhang** [comment]
Hi @BakingBrains,

The original script wasn't kept unfortunately. But you can easily reproduce the script by arranging the annotations in the same format. Annotations for each image is contained in a dictionary with the following keys:
```
boxes_h: List[List]
    Human bounding boxes
boxes_o: List[List]
    Object bounding boxes
hoi: List[int]
    Indices for ground truth interactions
object: List[int]
    Indices for object classes in each pair
verb: List[int]
    Indices for ground truth actions
```

Hope that helps.

Cheers,
Fred.
