### ISSUE TITLE
How to anntotate my own dataset as the form of hciodet?

### ISSUE THREAD

**Issue by Zhanyi0923** [fredzzhang/hicodet#27]
Nice work!
But I wonder how to make my own dataset  as the form of hciodet?

**Comment by fredzzhang** [comment]
Hi @Zhanyi0923,

You can try the annotation tools released by the authors.

**Comment by fredzzhang** [comment]
Hi @Zhanyi0923,

You can try the annotation tools released by the authors. https://github.com/ywchao/hoi-det-ui.

Fred.
