### ISSUE TITLE
main_detr.py line 22

### ISSUE THREAD

**Issue by roy881020** [fredzzhang/hicodet#31]
there is no module named 'util' in line 22

from util import box_ops

**Comment by fredzzhang** [comment]
Hi @roy881020,

The module `util` is part of the `detr` repository, which is included as a submodule. Can you check whether you have downloaded the submodule? If you did, the directory `detr` should not be empty.

You can download the submodule with `git submodule init` and `git submodule update`.

Fred.

**Comment by roy881020** [comment]
Thanks
