### ISSUE TITLE
zero-shot settings for HICO-DET

### ISSUE THREAD

**Issue by ZhouGuangP** [fredzzhang/hicodet#42]
Nice work! I want to conduct zero-shot experiments on the HICO-DET dataset, but I don't know how to generate the “.json” files for the unseen setting. Could you please provide the source code to generate the “instances_train2015.json” file? Or give me some guidance?

**Comment by fredzzhang** [comment]
Hi @ZhouGuangP,

Those files were generated too long ago. Sorry I don't have the scripts anymore.

The `.json` file itself is a dictionary with the following keys,
1. `annotation`: a list of dictionaries containing the annotations for all images. Each dictionary contains the bounding box coordinates (x1, y1, x2, y2), the HOI class index, object class index and the action class index.
2. `filenames`: a list of the image file names.
3. `empty`: a list of the indices corresponding to images without HOI annotation, which are automatically skipped.
4. `objects`: a list of object names.
5. `verbs`: a list of action names.
6. `correspondence`: a list of lists, with each list consisting of `[hoi_idx, verb_idx, obj_idx]`. This shows the correspondence between different elements of the same HOI triplet.
7. `size`: a list of image sizes (W, H).

Hope that helps.

Fred.
