### ISSUE TITLE
have some questions about instances_test2015.json.

### ISSUE THREAD

**Issue by AngleBeats147753** [fredzzhang/hicodet#44]
I am planning to replace HICO with my own dataset, but I'm currently confused about instances_test2015.json.
1. Are the boxes_h in xyxy format or xywh format, or Coco's x_min, y_min, w, h?
2. Does the origin of boxes_h start from (1, 1) or (0, 0)?

**Comment by fredzzhang** [comment]
Hi @AngleBeats147753,

The boxes are in xyxy format I believe.

The original annotations for HICO-DET encodes the box coordinates with one-based index. So I think it's also the case here.

Fred.
