### ISSUE TITLE
About hico-det Known object Setting

### ISSUE THREAD

**Issue by TCK2001** [fredzzhang/hicodet#46]
How to perform "known object Setting" on HICO-DET dataset ?

Many HOI (Human-Object Interaction) papers report experimental results for the known object setting, but they often don't explain how they implemented it...

thanks !

**Comment by fredzzhang** [comment]
Hi @TCK2001,

See [this post](https://github.com/fredzzhang/upt/discussions/38) for more details.

Fred.
